package OcsSNMPv1;


/**
* OcsSNMPv1/ASN_OID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public interface ASN_OID
{
  public static final short value = (short)(0x06);
}
