package OcsSNMPv1;


/**
* OcsSNMPv1/OctetSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class OctetSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public OctetSeqHolder ()
  {
  }

  public OctetSeqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OcsSNMPv1.OctetSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OcsSNMPv1.OctetSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OcsSNMPv1.OctetSeqHelper.type ();
  }

}
