package OcsSNMPv1;

/**
* OcsSNMPv1/SnmpVarBindHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class SnmpVarBindHolder implements org.omg.CORBA.portable.Streamable
{
  public OcsSNMPv1.SnmpVarBind value = null;

  public SnmpVarBindHolder ()
  {
  }

  public SnmpVarBindHolder (OcsSNMPv1.SnmpVarBind initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OcsSNMPv1.SnmpVarBindHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OcsSNMPv1.SnmpVarBindHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OcsSNMPv1.SnmpVarBindHelper.type ();
  }

}
