package OcsSNMPv1;


/**
* OcsSNMPv1/SnmpTrapProfileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public interface SnmpTrapProfileOperations 
{
  int getPort ();
  boolean addAgentAddress (String address);
  boolean removeAgentAddress (String address) throws OcsSNMPv1.NoSuchElement;
  String[] listAgentAddresses ();
  boolean addEnterpriseOID (String oid);
  boolean removeEnterpriseOID (String oid) throws OcsSNMPv1.NoSuchElement;
  String[] listEnterpriseOIDs ();
  boolean addGenericTrapType (int type);
  boolean removeGenericTrapType (int type) throws OcsSNMPv1.NoSuchElement;
  int[] listGenericTrapTypes ();
  boolean addSpecificTrapType (int type);
  boolean removeSpecificTrapType (int type) throws OcsSNMPv1.NoSuchElement;
  int[] listSpecificTrapTypes ();
  void destroy ();
} // interface SnmpTrapProfileOperations
