package OcsSNMPv1;

/**
* OcsSNMPv1/SnmpTrapEventHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class SnmpTrapEventHolder implements org.omg.CORBA.portable.Streamable
{
  public OcsSNMPv1.SnmpTrapEvent value = null;

  public SnmpTrapEventHolder ()
  {
  }

  public SnmpTrapEventHolder (OcsSNMPv1.SnmpTrapEvent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OcsSNMPv1.SnmpTrapEventHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OcsSNMPv1.SnmpTrapEventHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OcsSNMPv1.SnmpTrapEventHelper.type ();
  }

}
