package OcsSNMPv1;

/**
* OcsSNMPv1/SnmpCustomerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class SnmpCustomerHolder implements org.omg.CORBA.portable.Streamable
{
  public OcsSNMPv1.SnmpCustomer value = null;

  public SnmpCustomerHolder ()
  {
  }

  public SnmpCustomerHolder (OcsSNMPv1.SnmpCustomer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OcsSNMPv1.SnmpCustomerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OcsSNMPv1.SnmpCustomerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OcsSNMPv1.SnmpCustomerHelper.type ();
  }

}
