package OcsSNMPv1;


/**
* OcsSNMPv1/SocketProblem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class SocketProblem extends org.omg.CORBA.UserException
{

  public SocketProblem ()
  {
    super(SocketProblemHelper.id());
  } // ctor


  public SocketProblem (String $reason)
  {
    super(SocketProblemHelper.id() + "  " + $reason);
  } // ctor

} // class SocketProblem
