package OcsSNMPv1;


/**
* OcsSNMPv1/ASNValueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

abstract public class ASNValueHelper
{
  private static String  _id = "IDL:OcsSNMPv1/ASNValue:1.0";

  public static void insert (org.omg.CORBA.Any a, OcsSNMPv1.ASNValue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OcsSNMPv1.ASNValue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
      _disTypeCode0 = org.omg.CORBA.ORB.init ().create_alias_tc (OcsSNMPv1.ASNTypeHelper.id (), "ASNType", _disTypeCode0);
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [9];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for empty (case label OcsSNMPv1.ASN_NULL.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_NULL.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
      _members0[0] = new org.omg.CORBA.UnionMember (
        "empty",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for integer (case label OcsSNMPv1.ASN_INTEGER.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_INTEGER.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (OcsSNMPv1.OctetSeqHelper.id (), "OctetSeq", _tcOf_members0);
      _members0[1] = new org.omg.CORBA.UnionMember (
        "integer",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for octstr (case label OcsSNMPv1.ASN_OCTSTR.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_OCTSTR.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (OcsSNMPv1.OctetSeqHelper.id (), "OctetSeq", _tcOf_members0);
      _members0[2] = new org.omg.CORBA.UnionMember (
        "octstr",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for opaq (case label OcsSNMPv1.ASN_OPAQUE.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_OPAQUE.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (OcsSNMPv1.OctetSeqHelper.id (), "OctetSeq", _tcOf_members0);
      _members0[3] = new org.omg.CORBA.UnionMember (
        "opaq",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for ipaddress (case label OcsSNMPv1.ASN_IPADDRESS.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_IPADDRESS.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[4] = new org.omg.CORBA.UnionMember (
        "ipaddress",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for oid (case label OcsSNMPv1.ASN_OID.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_OID.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
      _members0[5] = new org.omg.CORBA.UnionMember (
        "oid",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for counter (case label OcsSNMPv1.ASN_COUNTER.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_COUNTER.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
      _members0[6] = new org.omg.CORBA.UnionMember (
        "counter",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for gauge (case label OcsSNMPv1.ASN_GAUGE.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_GAUGE.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
      _members0[7] = new org.omg.CORBA.UnionMember (
        "gauge",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for timeticks (case label OcsSNMPv1.ASN_TIMETICKS.value)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      _anyOf_members0.insert_short ((short)OcsSNMPv1.ASN_TIMETICKS.value);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
      _members0[8] = new org.omg.CORBA.UnionMember (
        "timeticks",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (OcsSNMPv1.ASNValueHelper.id (), "ASNValue", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OcsSNMPv1.ASNValue read (org.omg.CORBA.portable.InputStream istream)
  {
    OcsSNMPv1.ASNValue value = new OcsSNMPv1.ASNValue ();
    short _dis0 = (short)0;
    _dis0 = istream.read_short ();
    switch (_dis0)
    {
      case OcsSNMPv1.ASN_NULL.value:
        byte _empty = (byte)0;
        _empty = istream.read_octet ();
        value.empty (_empty);
        break;
      case OcsSNMPv1.ASN_INTEGER.value:
        byte _integer[] = null;
        _integer = OcsSNMPv1.OctetSeqHelper.read (istream);
        value.integer (_integer);
        break;
      case OcsSNMPv1.ASN_OCTSTR.value:
        byte _octstr[] = null;
        _octstr = OcsSNMPv1.OctetSeqHelper.read (istream);
        value.octstr (_octstr);
        break;
      case OcsSNMPv1.ASN_OPAQUE.value:
        byte _opaq[] = null;
        _opaq = OcsSNMPv1.OctetSeqHelper.read (istream);
        value.opaq (_opaq);
        break;
      case OcsSNMPv1.ASN_IPADDRESS.value:
        String _ipaddress = null;
        _ipaddress = istream.read_string ();
        value.ipaddress (_ipaddress);
        break;
      case OcsSNMPv1.ASN_OID.value:
        String _oid = null;
        _oid = istream.read_string ();
        value.oid (_oid);
        break;
      case OcsSNMPv1.ASN_COUNTER.value:
        int _counter = (int)0;
        _counter = istream.read_ulong ();
        value.counter (_counter);
        break;
      case OcsSNMPv1.ASN_GAUGE.value:
        int _gauge = (int)0;
        _gauge = istream.read_ulong ();
        value.gauge (_gauge);
        break;
      case OcsSNMPv1.ASN_TIMETICKS.value:
        int _timeticks = (int)0;
        _timeticks = istream.read_ulong ();
        value.timeticks (_timeticks);
        break;
      default:
        value._default( _dis0 ) ;
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OcsSNMPv1.ASNValue value)
  {
    ostream.write_short (value.discriminator ());
    switch (value.discriminator ())
    {
      case OcsSNMPv1.ASN_NULL.value:
        ostream.write_octet (value.empty ());
        break;
      case OcsSNMPv1.ASN_INTEGER.value:
        OcsSNMPv1.OctetSeqHelper.write (ostream, value.integer ());
        break;
      case OcsSNMPv1.ASN_OCTSTR.value:
        OcsSNMPv1.OctetSeqHelper.write (ostream, value.octstr ());
        break;
      case OcsSNMPv1.ASN_OPAQUE.value:
        OcsSNMPv1.OctetSeqHelper.write (ostream, value.opaq ());
        break;
      case OcsSNMPv1.ASN_IPADDRESS.value:
        ostream.write_string (value.ipaddress ());
        break;
      case OcsSNMPv1.ASN_OID.value:
        ostream.write_string (value.oid ());
        break;
      case OcsSNMPv1.ASN_COUNTER.value:
        ostream.write_ulong (value.counter ());
        break;
      case OcsSNMPv1.ASN_GAUGE.value:
        ostream.write_ulong (value.gauge ());
        break;
      case OcsSNMPv1.ASN_TIMETICKS.value:
        ostream.write_ulong (value.timeticks ());
        break;
    }
  }

}
