package OcsSNMPv1;


/**
* OcsSNMPv1/ASNValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class ASNValue implements org.omg.CORBA.portable.IDLEntity
{
  private byte ___empty;
  private byte[] ___integer;
  private byte[] ___octstr;
  private byte[] ___opaq;
  private String ___ipaddress;
  private String ___oid;
  private int ___counter;
  private int ___gauge;
  private int ___timeticks;
  private short __discriminator;
  private boolean __uninitialized = true;

  public ASNValue ()
  {
  }

  public short discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public byte empty ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyempty (__discriminator);
    return ___empty;
  }

  public void empty (byte value)
  {
    __discriminator = OcsSNMPv1.ASN_NULL.value;
    ___empty = value;
    __uninitialized = false;
  }

  public void empty (short discriminator, byte value)
  {
    verifyempty (discriminator);
    __discriminator = discriminator;
    ___empty = value;
    __uninitialized = false;
  }

  private void verifyempty (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_NULL.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public byte[] integer ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyinteger (__discriminator);
    return ___integer;
  }

  public void integer (byte[] value)
  {
    __discriminator = OcsSNMPv1.ASN_INTEGER.value;
    ___integer = value;
    __uninitialized = false;
  }

  public void integer (short discriminator, byte[] value)
  {
    verifyinteger (discriminator);
    __discriminator = discriminator;
    ___integer = value;
    __uninitialized = false;
  }

  private void verifyinteger (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_INTEGER.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public byte[] octstr ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyoctstr (__discriminator);
    return ___octstr;
  }

  public void octstr (byte[] value)
  {
    __discriminator = OcsSNMPv1.ASN_OCTSTR.value;
    ___octstr = value;
    __uninitialized = false;
  }

  public void octstr (short discriminator, byte[] value)
  {
    verifyoctstr (discriminator);
    __discriminator = discriminator;
    ___octstr = value;
    __uninitialized = false;
  }

  private void verifyoctstr (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_OCTSTR.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public byte[] opaq ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyopaq (__discriminator);
    return ___opaq;
  }

  public void opaq (byte[] value)
  {
    __discriminator = OcsSNMPv1.ASN_OPAQUE.value;
    ___opaq = value;
    __uninitialized = false;
  }

  public void opaq (short discriminator, byte[] value)
  {
    verifyopaq (discriminator);
    __discriminator = discriminator;
    ___opaq = value;
    __uninitialized = false;
  }

  private void verifyopaq (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_OPAQUE.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String ipaddress ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyipaddress (__discriminator);
    return ___ipaddress;
  }

  public void ipaddress (String value)
  {
    __discriminator = OcsSNMPv1.ASN_IPADDRESS.value;
    ___ipaddress = value;
    __uninitialized = false;
  }

  public void ipaddress (short discriminator, String value)
  {
    verifyipaddress (discriminator);
    __discriminator = discriminator;
    ___ipaddress = value;
    __uninitialized = false;
  }

  private void verifyipaddress (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_IPADDRESS.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String oid ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyoid (__discriminator);
    return ___oid;
  }

  public void oid (String value)
  {
    __discriminator = OcsSNMPv1.ASN_OID.value;
    ___oid = value;
    __uninitialized = false;
  }

  public void oid (short discriminator, String value)
  {
    verifyoid (discriminator);
    __discriminator = discriminator;
    ___oid = value;
    __uninitialized = false;
  }

  private void verifyoid (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_OID.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public int counter ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifycounter (__discriminator);
    return ___counter;
  }

  public void counter (int value)
  {
    __discriminator = OcsSNMPv1.ASN_COUNTER.value;
    ___counter = value;
    __uninitialized = false;
  }

  public void counter (short discriminator, int value)
  {
    verifycounter (discriminator);
    __discriminator = discriminator;
    ___counter = value;
    __uninitialized = false;
  }

  private void verifycounter (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_COUNTER.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public int gauge ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifygauge (__discriminator);
    return ___gauge;
  }

  public void gauge (int value)
  {
    __discriminator = OcsSNMPv1.ASN_GAUGE.value;
    ___gauge = value;
    __uninitialized = false;
  }

  public void gauge (short discriminator, int value)
  {
    verifygauge (discriminator);
    __discriminator = discriminator;
    ___gauge = value;
    __uninitialized = false;
  }

  private void verifygauge (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_GAUGE.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public int timeticks ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifytimeticks (__discriminator);
    return ___timeticks;
  }

  public void timeticks (int value)
  {
    __discriminator = OcsSNMPv1.ASN_TIMETICKS.value;
    ___timeticks = value;
    __uninitialized = false;
  }

  public void timeticks (short discriminator, int value)
  {
    verifytimeticks (discriminator);
    __discriminator = discriminator;
    ___timeticks = value;
    __uninitialized = false;
  }

  private void verifytimeticks (short discriminator)
  {
    if (discriminator != OcsSNMPv1.ASN_TIMETICKS.value)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public void _default ()
  {
    __discriminator = -32768;
    __uninitialized = false;
  }

  public void _default (short discriminator)
  {
    verifyDefault( discriminator ) ;
    __discriminator = discriminator ;
    __uninitialized = false;
  }

  private void verifyDefault( short value )
  {
    switch (value) {
      case OcsSNMPv1.ASN_NULL.value:
      case OcsSNMPv1.ASN_INTEGER.value:
      case OcsSNMPv1.ASN_OCTSTR.value:
      case OcsSNMPv1.ASN_OPAQUE.value:
      case OcsSNMPv1.ASN_IPADDRESS.value:
      case OcsSNMPv1.ASN_OID.value:
      case OcsSNMPv1.ASN_COUNTER.value:
      case OcsSNMPv1.ASN_GAUGE.value:
      case OcsSNMPv1.ASN_TIMETICKS.value:
        throw new org.omg.CORBA.BAD_OPERATION() ;

      default:
        return;
    }
  }

} // class ASNValue
