package OcsSNMPv1;


/**
* OcsSNMPv1/DETOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public interface DETOperations 
{
  int buyItem (String item, int qty);
  int printReport ();

  //long sellItem(int String item, in long qty,in double bal);
  int sellItem (int qty, double bal);
  int tradeItems (String item1, int qty1, String item2, int qty2, String etrader);
} // interface DETOperations
