package OcsSNMPv1;


/**
* OcsSNMPv1/RequestType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public class RequestType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static OcsSNMPv1.RequestType[] __array = new OcsSNMPv1.RequestType [__size];

  public static final int _SNMP_GET = 0;
  public static final OcsSNMPv1.RequestType SNMP_GET = new OcsSNMPv1.RequestType(_SNMP_GET);
  public static final int _SNMP_GET_NEXT = 1;
  public static final OcsSNMPv1.RequestType SNMP_GET_NEXT = new OcsSNMPv1.RequestType(_SNMP_GET_NEXT);

  public int value ()
  {
    return __value;
  }

  public static OcsSNMPv1.RequestType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected RequestType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class RequestType
