package OcsSNMPv1;


/**
* OcsSNMPv1/SnmpTrapListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public interface SnmpTrapListenerOperations 
{
  void trapReceived (OcsSNMPv1.SnmpTrapEvent evt);
} // interface SnmpTrapListenerOperations
