package OcsSNMPv1;


/**
* OcsSNMPv1/SnmpTrapEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public final class SnmpTrapEvent implements org.omg.CORBA.portable.IDLEntity
{
  public String address = null;
  public int port = (int)0;
  public String enterpriseOID = null;
  public int timestamp = (int)0;
  public boolean isGeneric = false;
  public int genericType = (int)0;
  public int specificType = (int)0;
  public OcsSNMPv1.SnmpVarBind varbinds[] = null;

  public SnmpTrapEvent ()
  {
  } // ctor

  public SnmpTrapEvent (String _address, int _port, String _enterpriseOID, int _timestamp, boolean _isGeneric, int _genericType, int _specificType, OcsSNMPv1.SnmpVarBind[] _varbinds)
  {
    address = _address;
    port = _port;
    enterpriseOID = _enterpriseOID;
    timestamp = _timestamp;
    isGeneric = _isGeneric;
    genericType = _genericType;
    specificType = _specificType;
    varbinds = _varbinds;
  } // ctor

} // class SnmpTrapEvent
