package OcsSNMPv1;


/**
* OcsSNMPv1/SnmpTrapProfileFactoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OcsSNMPv1.idl
* Monday, January 26, 2009 4:24:09 o'clock PM EST
*/

public abstract class SnmpTrapProfileFactoryPOA extends org.omg.PortableServer.Servant
 implements OcsSNMPv1.SnmpTrapProfileFactoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createProfile", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // OcsSNMPv1/SnmpTrapProfileFactory/createProfile
       {
         int port = in.read_ulong ();
         OcsSNMPv1.SnmpTrapProfile $result = null;
         $result = this.createProfile (port);
         out = $rh.createReply();
         OcsSNMPv1.SnmpTrapProfileHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OcsSNMPv1/SnmpTrapProfileFactory:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SnmpTrapProfileFactory _this() 
  {
    return SnmpTrapProfileFactoryHelper.narrow(
    super._this_object());
  }

  public SnmpTrapProfileFactory _this(org.omg.CORBA.ORB orb) 
  {
    return SnmpTrapProfileFactoryHelper.narrow(
    super._this_object(orb));
  }


} // class SnmpTrapProfileFactoryPOA
