package DETApp;


/**
* DETApp/_DETStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Sunday, March 8, 2009 10:30:35 o'clock PM EDT
*/

public class _DETStub extends org.omg.CORBA.portable.ObjectImpl implements DETApp.DET
{

  public int SnmpSetBalance ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("SnmpSetBalance", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return SnmpSetBalance (        );
            } finally {
                _releaseReply ($in);
            }
  } // SnmpSetBalance

  public int buyItem (String item, int qty)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buyItem", true);
                $out.write_string (item);
                $out.write_long (qty);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buyItem (item, qty        );
            } finally {
                _releaseReply ($in);
            }
  } // buyItem

  public int printReport ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("printReport", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return printReport (        );
            } finally {
                _releaseReply ($in);
            }
  } // printReport

  public int printReportAfterTransaction ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("printReportAfterTransaction", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return printReportAfterTransaction (        );
            } finally {
                _releaseReply ($in);
            }
  } // printReportAfterTransaction

  public void trapBalance ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("trapBalance", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                trapBalance (        );
            } finally {
                _releaseReply ($in);
            }
  } // trapBalance


  //long sellItem(int String item, in long qty,in double bal);
  public int sellItem (int qty, double bal)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sellItem", true);
                $out.write_long (qty);
                $out.write_double (bal);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sellItem (qty, bal        );
            } finally {
                _releaseReply ($in);
            }
  } // sellItem

  public int tradeItems (String item1, int qty1, String item2, int qty2, String etrader)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("tradeItems", true);
                $out.write_string (item1);
                $out.write_long (qty1);
                $out.write_string (item2);
                $out.write_long (qty2);
                $out.write_string (etrader);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return tradeItems (item1, qty1, item2, qty2, etrader        );
            } finally {
                _releaseReply ($in);
            }
  } // tradeItems


  //string snmpSetRequest(in double bal) ;
  public boolean snmpSentRequestToServer1 (String item1)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpSentRequestToServer1", true);
                $out.write_string (item1);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpSentRequestToServer1 (item1        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpSentRequestToServer1

  public boolean snmpSentRequestToServer2 (String item2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpSentRequestToServer2", true);
                $out.write_string (item2);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpSentRequestToServer2 (item2        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpSentRequestToServer2

  public int getPrintReportFromServer1 ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPrintReportFromServer1", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPrintReportFromServer1 (        );
            } finally {
                _releaseReply ($in);
            }
  } // getPrintReportFromServer1

  public int getPrintReportFromServer2 ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPrintReportFromServer2", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPrintReportFromServer2 (        );
            } finally {
                _releaseReply ($in);
            }
  } // getPrintReportFromServer2


  //string snmpGetRequestSysDescription(in string sysDescription, in string item1);
  public String snmpGetRequestSysDescription (String item2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpGetRequestSysDescription", true);
                $out.write_string (item2);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpGetRequestSysDescription (item2        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpGetRequestSysDescription

  public String snmpGetRequestSysContact (String item2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpGetRequestSysContact", true);
                $out.write_string (item2);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpGetRequestSysContact (item2        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpGetRequestSysContact

  public String snmpGetRequestSysName (String item2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpGetRequestSysName", true);
                $out.write_string (item2);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpGetRequestSysName (item2        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpGetRequestSysName

  public String snmpGetRequestSysLocation (String item2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpGetRequestSysLocation", true);
                $out.write_string (item2);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpGetRequestSysLocation (item2        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpGetRequestSysLocation

  public String snmpGetRequestSysServiceInfo (String item2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("snmpGetRequestSysServiceInfo", true);
                $out.write_string (item2);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return snmpGetRequestSysServiceInfo (item2        );
            } finally {
                _releaseReply ($in);
            }
  } // snmpGetRequestSysServiceInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DETApp/DET:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _DETStub
