package DETApp;


/**
* DETApp/DET.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Sunday, March 8, 2009 10:30:35 o'clock PM EDT
*/

public interface DET extends DETOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DET
