package DETApp;

/**
* DETApp/DETHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Sunday, March 8, 2009 10:30:35 o'clock PM EDT
*/

public final class DETHolder implements org.omg.CORBA.portable.Streamable
{
  public DETApp.DET value = null;

  public DETHolder ()
  {
  }

  public DETHolder (DETApp.DET initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DETApp.DETHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DETApp.DETHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DETApp.DETHelper.type ();
  }

}
