package DETApp;


/**
* DETApp/DETPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DET.idl
* Sunday, March 8, 2009 10:30:35 o'clock PM EDT
*/

public abstract class DETPOA extends org.omg.PortableServer.Servant
 implements DETApp.DETOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("SnmpSetBalance", new java.lang.Integer (0));
    _methods.put ("buyItem", new java.lang.Integer (1));
    _methods.put ("printReport", new java.lang.Integer (2));
    _methods.put ("printReportAfterTransaction", new java.lang.Integer (3));
    _methods.put ("trapBalance", new java.lang.Integer (4));
    _methods.put ("sellItem", new java.lang.Integer (5));
    _methods.put ("tradeItems", new java.lang.Integer (6));
    _methods.put ("snmpSentRequestToServer1", new java.lang.Integer (7));
    _methods.put ("snmpSentRequestToServer2", new java.lang.Integer (8));
    _methods.put ("getPrintReportFromServer1", new java.lang.Integer (9));
    _methods.put ("getPrintReportFromServer2", new java.lang.Integer (10));
    _methods.put ("snmpGetRequestSysDescription", new java.lang.Integer (11));
    _methods.put ("snmpGetRequestSysContact", new java.lang.Integer (12));
    _methods.put ("snmpGetRequestSysName", new java.lang.Integer (13));
    _methods.put ("snmpGetRequestSysLocation", new java.lang.Integer (14));
    _methods.put ("snmpGetRequestSysServiceInfo", new java.lang.Integer (15));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DETApp/DET/SnmpSetBalance
       {
         int $result = (int)0;
         $result = this.SnmpSetBalance ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // DETApp/DET/buyItem
       {
         String item = in.read_string ();
         int qty = in.read_long ();
         int $result = (int)0;
         $result = this.buyItem (item, qty);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // DETApp/DET/printReport
       {
         int $result = (int)0;
         $result = this.printReport ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // DETApp/DET/printReportAfterTransaction
       {
         int $result = (int)0;
         $result = this.printReportAfterTransaction ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // DETApp/DET/trapBalance
       {
         this.trapBalance ();
         out = $rh.createReply();
         break;
       }


  //long sellItem(int String item, in long qty,in double bal);
       case 5:  // DETApp/DET/sellItem
       {
         int qty = in.read_long ();
         double bal = in.read_double ();
         int $result = (int)0;
         $result = this.sellItem (qty, bal);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // DETApp/DET/tradeItems
       {
         String item1 = in.read_string ();
         int qty1 = in.read_long ();
         String item2 = in.read_string ();
         int qty2 = in.read_long ();
         String etrader = in.read_string ();
         int $result = (int)0;
         $result = this.tradeItems (item1, qty1, item2, qty2, etrader);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //string snmpSetRequest(in double bal) ;
       case 7:  // DETApp/DET/snmpSentRequestToServer1
       {
         String item1 = in.read_string ();
         boolean $result = false;
         $result = this.snmpSentRequestToServer1 (item1);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // DETApp/DET/snmpSentRequestToServer2
       {
         String item2 = in.read_string ();
         boolean $result = false;
         $result = this.snmpSentRequestToServer2 (item2);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // DETApp/DET/getPrintReportFromServer1
       {
         int $result = (int)0;
         $result = this.getPrintReportFromServer1 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 10:  // DETApp/DET/getPrintReportFromServer2
       {
         int $result = (int)0;
         $result = this.getPrintReportFromServer2 ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }


  //string snmpGetRequestSysDescription(in string sysDescription, in string item1);
       case 11:  // DETApp/DET/snmpGetRequestSysDescription
       {
         String item2 = in.read_string ();
         String $result = null;
         $result = this.snmpGetRequestSysDescription (item2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 12:  // DETApp/DET/snmpGetRequestSysContact
       {
         String item2 = in.read_string ();
         String $result = null;
         $result = this.snmpGetRequestSysContact (item2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 13:  // DETApp/DET/snmpGetRequestSysName
       {
         String item2 = in.read_string ();
         String $result = null;
         $result = this.snmpGetRequestSysName (item2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 14:  // DETApp/DET/snmpGetRequestSysLocation
       {
         String item2 = in.read_string ();
         String $result = null;
         $result = this.snmpGetRequestSysLocation (item2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 15:  // DETApp/DET/snmpGetRequestSysServiceInfo
       {
         String item2 = in.read_string ();
         String $result = null;
         $result = this.snmpGetRequestSysServiceInfo (item2);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DETApp/DET:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DET _this() 
  {
    return DETHelper.narrow(
    super._this_object());
  }

  public DET _this(org.omg.CORBA.ORB orb) 
  {
    return DETHelper.narrow(
    super._this_object(orb));
  }


} // class DETPOA
